### PR TITLE
Add data.csv

### PR DESCRIPTION
**Pull request by eMerzh**
@vdarmsta here is a start for no-wikidata rows

### CODE REVIEW

**Comment by eMerzh** [comment]
i said that but maybe @jbelien can merge that too 🤷  no idea who maintain this currently

**Comment by jbelien** [comment]
Thanks @eMerzh !

@vdarmsta is in charge of this repository 😄 (but I can take care of the merge if needed).

**Review by jbelien — CHANGES_REQUESTED** [review]
Could you limit the PR to `data.csv` file, the other files will be updated automatically ?
Thanks!

**Comment by eMerzh** [comment]
ofc, here it is... i wanted to update them as there are a few changes, but i guess next month is ok 🤷

**Comment by eMerzh** [comment]
wondering if we could'nt but the build also on push data.csv like

```yaml
on:
  push:
    paths:
      - 'data.csv'
```

**Comment by jbelien** [comment]
> wondering if we could'nt but the build also on push data.csv like [...]

Yep, that was indeed my plan! 👍

**Review by jbelien — APPROVED** [review]

**Comment by eMerzh** [comment]
whoo .. thanks @jbelien 🙏

**Comment by vdarmsta** [comment]
> Thanks @eMerzh !
> 
> @vdarmsta is in charge of this repository 😄 (but I can take care of the merge if needed).

Thank you very much both of you. I'm indeed in charge of the repository, but I still have a lot to learn about github.... So, you help is very much appreciated.

**Comment by vdarmsta** [comment]
> whoo .. thanks @jbelien 🙏

Yes, indeed, thank you very much. This looks really great like that and I know how to increase the number of streets taken into account. Will try to add more streets asap.

**Pull request merged**
